### ISSUE TITLE
x.com design inconsistency

### ISSUE THREAD

**Issue by Ecoder-web** [sameerasw/my-internet#1338]
**Describe the bug**
Inconsistency in the twitter website. Some have black bars and others have readability/visibility issues on certain backgrounds.

**To Reproduce**
1. Go x.com

**Expected behavior**
Better readability and consistent design

**Screenshots**
Part 1
When replying under a post there is a bar under
![Image](https://github.com/user-attachments/assets/4d75d6b3-3f70-4357-a691-12d5027b0f90)

Part 2
Quoted retweets can morph into the background with no clear borders on some wallpapers

Part 3
Links between replies in posts face same issue as Part 2
![Image](https://github.com/user-attachments/assets/9a9a34e5-f19d-40d7-91d5-2087ad404d8b)

Part 4
Search bar and containers on right bar have black backgrounds
![Image](https://github.com/user-attachments/assets/601cc807-a699-41f9-9c58-2a7f1db615fb)
![Image](https://github.com/user-attachments/assets/a46f73a4-dbfd-427b-afff-d332fc76da41)

**Desktop (please complete the following information):**
Zen Version 1.12.10b

**Additional context**
I tried reading the guide for contribution but I am not sure if I should attach this
However, I was able to fix my issues using these snippets
It is to be noted that I did not spend a lot of time deciding colors
``` css
.r-1bnu78o {
/* Part 3*/
  background-color: rgb(174, 174, 174) !important;
}

.r-1kqtdi0 {
/* Part 2 and 4 */
  border-color: rgb(41, 67, 89) !important;
  background: rgb(41, 67, 89, 0.05) !important
}

.r-kemksi {

/* Part 2 and 4 */
  border-color: rgb(41, 67, 89) !important;

/* Part 1*/
  background-color: transparent !important;
}

```
