### ISSUE TITLE
web.whatsapp.com need more improvement in terms of consistency in chat and profile window

### ISSUE THREAD

**Issue by gmiqbal** [sameerasw/my-internet#296]

**Comment by sameerasw** [comment]
I don't use WhatsApp on web enough for this, But I will check out if possible later.

**Comment by Waltorvi** [comment]
Hello! I try to make it full transparent and better. But this is very difficult, may be impossible, because whatsapp web has a dynamic classes. That's my solution for chat list and user/group page:
```css
.dark {
        /* redefine variables */
        /* for chat list */
        --background-default-active: rgba(0, 0, 0, 0.3) !important;
        --background-default-hover: rgba(0, 0, 0, 0.2) !important;
        
        /* for user/group info tab | This is also background for other tabs like 'status' */
        --background-document-with-captions: rgba(0, 0, 0, 0.3) !important;
    }
    
    /*for chat list */
    #pane-side div[role="listitem"] > div > div > div > div {
        border-top: solid transparent !important;
    }
    
    /* for user/group info tab, but also affects other tabs like 'status' */
    .copyable-area section > div {
        box-shadow: none !important;
    }
```
But 'status' and 'community' tabs have the same code as the user info tab, which is why their background is transparent. The problem here is that these tabs overlap the chat tab, which is why they blend together. This could be fixed if there weren't so many dynamic classes. But maybe I just don't have enough experience in css

![Image](https://github.com/user-attachments/assets/893492e8-3bdc-4e5b-8ad7-9a988a4b7df0)

I hope I helped you in writing whatsapp style
