### ISSUE TITLE
[THEME] my.headspace.com

### ISSUE THREAD

**Issue by Aditya-Raj-Tiwari** [sameerasw/my-internet#348]
Please add a theme for my.headspace.com

```css
/* ==UserStyle==
@name           my.headspace.com/modes/meditate
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         Me
==/UserStyle== */

@-moz-document url-prefix("https://my.headspace.com/modes/meditate") {
    /* Insert code here... */
}

span,h2,h1{
    color:#fff !important;
}

button span, .css-dvoshi span{
    color:#000 !important;
}

h3 > a{
    color:#fff !important;
}

header > *, header path{
    color: #fff !important;
    fill: #fff !important;
}
```
