### ISSUE TITLE
Glance animation broken

### ISSUE THREAD

**Issue by naman-seth** [sameerasw/my-internet#71]
**Describe the bug**
Glance animation is not working correctly due to following code in [userChrome.css](https://github.com/sameerasw/my-internet/blob/0319a3b6beb10fdd5632e123d7b5b651f395a852/userChrome.css)

```css
/* website view animations */
#browser .browserContainer{
	transition: all 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.35) !important;
}
``` 

**Desktop :**
 - OS: [Windows]
 - Browser [Zen]
 - Version [1.8.2b]
